### ISSUE TITLE
Linear thermal expansion for low density polyethylene

### ISSUE THREAD

**Issue by feeskoum** [dudung/datasets#1]
I would like to submit dataset with following information
+ feature: temperature, coefficient of linear thermal expansion
+ material: low density polyethylene
+ origin: https://www.researchgate.net/publication/235140170
+ metadata: `polyethylene_low_density.json`
```json
{
  "creator": ["James R. Asay", "S. R. Urzendowski", "Arthur H. Guenther"],
  "date": "1968-01-00 00:00",
  "origin": "https://www.researchgate.net/publication/235140170",
  "element": "Table 15, Page 86", 
  "material": "Low density polyethylene",
  "specimen": 0,
  "editor": "Fees Koum",
  "update": "2024-04-17 05:23",
  "delimiter": "comma",
  "column": ["Temperature", "Coefficent of linear thermal expansion"],
  "type": ["float", "float"],
  "unit": ["°C", "1E5 in/in·°C"],
  "data": "polyethylene_low_density.csv"
}
```
+ file: [polyethylene_low_density.csv](https://github.com/dudung/datasets/files/15003528/polyethylene_low_density.csv)

**Comment by dudung** [comment]
+ I have check the JSON and CSV files. All look correct.
+ Do you have any idea about folder name under [`data`](https://github.com/dudung/datasets/tree/main/data)? How about `linear_thermal_expansion`? Is it adequate?
+ Please propose another folder name or confirm the suggested name. Thank you.

**Comment by feeskoum** [comment]
@dudung, I confirm `linear_thermal_expansion` as the folder name under `data`. Thanks.

**Comment by dudung** [comment]
@feeskoum, I have made the folder \
https://github.com/dudung/datasets/tree/main/data/linear_thermal_expansion

Please follow the steps below.

+ Refresh your browser to see notification.
  - Click Sync &rightarrow; Update branch.
  - Navigate to the new folder.
+ Upload your JSON dan CSV files.
  - Click + &rightarrow; Upload files.
  - Please use the same filename, e.g. `something.csv` and `something.json`.
  - Drag and drop the files from your computer.
  - Click Commit changes at the bottom.
+ Refresh your browser to see notification.
  - Click Contribute &rightarrow; Open pull request.
  - Click Create pull request.
  - Confirm and click Create pull request at the bottom.

**Comment by dudung** [comment]
I have merged you contribution, @feeskoum. Thanks.

https://github.com/dudung/datasets/tree/main/data/linear_thermal_expansion
